spring.application.name=audit-service

server.port=8080

spring.datasource.url=jdbc:h2:mem:auditdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-audit

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672